
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@doe.com",
    "password": "Password123.",
    "confirmPassword": "Password123."
}


POST http://localhost:3000/users/create-many
Content-Type: application/json

{
    "users": [
    {
    "firstName": "smith",
    "lastName": "Doe",
    "email": "dick2@hnotmail.com",
    "password": "Password123."
    },
    {
    "firstName": "shit",
    "lastName": "Doe",
    "email": "212312@hnotmail.com",
    "password": "Password123."
    }
    ]

}